### ISSUE TITLE
Docs page 404

### ISSUE THREAD

**Issue by ProFireDev** [VukkyLtd/vukkyltd.xyz#1]
The documentation page is missing from the site. A lot of the links seem to not be working aswell.

![Screenshot_20210214-131115.png](https://user-images.githubusercontent.com/34112557/107887838-251a6980-6ec6-11eb-808b-5c6972f0c2c5.png)

^ this page is for the get vukky bot link

**Comment by viluzi** [comment]
Hello! This is not an issue of vukkyltd really, except it is. its because Vukky redesigned his site and killed that page
